services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    
    image: nextjs-app:latest
    
    environment:
      NODE_ENV: production
      PORT: 3000
    
    # ✅ Réseau bridge classique au lieu de Swarm overlay
    networks:
      - dokploy-network
    
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # ❌ SUPPRIMEZ la section deploy: (spécifique Swarm)
    restart: unless-stopped
    
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'

networks:
  dokploy-network:
    external: true