services:
  nextjs:
    image: nextjs-app:latest
    container_name: nextjs-app  # ← Nom fixe

    build:
      context: .
      dockerfile: Dockerfile
    
    environment:
      NODE_ENV: production
      PORT: 3000
    
    networks:
      - dokploy-network
    
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
      placement:
        constraints:
          - node.role == manager
    
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'

networks:
  dokploy-network:
    external: true