services:
  nextjs:
    image: portfolio-lucasgiza-frontend-vxoi1z:latest
    
    environment:
      NODE_ENV: production
      PORT: 3000
    
    networks:
      dokploy-network:
        aliases:
          - nextjs-app
    
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 1024M
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'

networks:
  dokploy-network:
    external: true