export const APP_SECTIONS = {
  HOME: 'home',
  ABOUT: 'about',
  EXPERIENCE: 'experience',
  PROJECTS: 'projects',
  PERSONAL_PROJECTS: 'personal-projects',
  SKILLS: 'skills'
};

export const SECTION_ORDER = [
  APP_SECTIONS.HOME,
  APP_SECTIONS.ABOUT,
  APP_SECTIONS.EXPERIENCE,
  APP_SECTIONS.SKILLS,
  APP_SECTIONS.PROJECTS,
  APP_SECTIONS.PERSONAL_PROJECTS,
];
